package com.example.domain.exception

import org.valiktor.DefaultConstraintViolation


open class Failure(
): Throwable()

